### ISSUE TITLE
Support Thundercore referrral Programme

### ISSUE THREAD

**Issue by Kisgus** [LinkdropProtocol/volca-linkdrop-core#4]
@Dobrokhvalov 

- [x] Web app thundercore support (dev)
- [x] Deploy backend 
- [x] Update endpoint to thundercore backend
- [x] Deploy basic thunder linkdrop 
- [x] Update referral program: ERC20 -> TT (native token like ETH)
- [x] Deploy front-end on github pages
- [x] Setup example referral program 
- [x] Update assets for the front-end app
- [x] Update front-end network
- [x] Update front-end lib end-point +

**Comment by mikhaildobs** [comment]
The Thundercore referral demo is live at https://thundercore.volca.app/#/auth?ref=0xff8cc9b005ba7e95d9e7c905a0be966d4febae2ac41f84f9911cd22f71811d71
